uploads = []
outputs = []

[[generated]]
id = "5k6TidBqQ25ajvpf_lIop"
uri = "file://public/ind-automotive.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ULI9gFm8Mj6RNjWFVQwRT"
uri = "file://public/ind-aerospace.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NKCqFXCu96OAj9xI3ZpD1"
uri = "file://public/ind-electro.png"
type = "image"
title = "generated_image"

[[generated]]
id = "l_Iya6B3ewdsLo2TCxNFw"
uri = "file://public/ind-medical.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CHKmYXBvveTlj1vDig-YZ"
uri = "file://public/ind-consumer.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4l37zJdYzwrf2dy4gO94y"
uri = "file://public/ind-heavy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xhtCNRrdRqAGpsOh3kfH3"
uri = "file://public/executives/sacheen.png"
type = "image"
title = "sacheen executive portrait"

[[generated]]
id = "acCXPtWRV_fK1xZg2SN0f"
uri = "file://public/executives/dileesh.png"
type = "image"
title = "dileesh executive portrait"

[[generated]]
id = "VO7RJ7n-yvnvBAXkFFZ3D"
uri = "file://public/executives/vipin.png"
type = "image"
title = "vipin executive portrait"

[[generated]]
id = "IUSSM5e-ize606JYhAGmo"
uri = "file://public/executives/icon-sacheen.png"
type = "image"
title = "user avatar icon blue"

[[generated]]
id = "-koX97VpodY6-H-ao_mBJ"
uri = "file://public/executives/icon-dileesh.png"
type = "image"
title = "user avatar icon navy tie"

[[generated]]
id = "I4dY7c_LJxfo8BFu-VkVd"
uri = "file://public/executives/icon-vipin.png"
type = "image"
title = "user avatar icon steel blue"
